### ISSUE TITLE
The custom possibility for the config change?

### ISSUE THREAD

**Issue by kukrik** [qcubed/plugin_ckeditor#9]
I appeal again with the some issues. Apparently, this is my problem that I do not understand how to use correctly function for `ReadyFunction`. I've tried several variations. And I researched CKEditor API, etc...

Unfortunately, the different solutions does not work...

Debugging provides with various solutions for almost one and the same error message: `Uncaught The editor instance "c1" is already attached to the provided element`. 

Just one simple example, which is certainly not the right solution: 

```
$this->txtEditor = new QCKEditor($this);
$this->txtEditor->ReadyFunction = sprintf('function(){CKEDITOR.replace("%s", {uiColor: "#CCEAEE"});}', $this->txtEditor->ControlId);
......................................
...................................... etc
```

Such raw javascript in website http://docs.ckeditor.com/#!/guide/dev_configuration:

```
CKEDITOR.replace( 'editor1', {
    language: 'fr',
    uiColor: '#9AB8F3'
});
```

My thought is this, if simple example works, then you may go forward to the desired solution, something similar: 

```
$this->txtEditor->ReadyFunction = sprintf('function(){CKEDITOR.replace("%s", customConfig: %s);}', $this->txtEditor->ControlId, __APP_JS_ASSETS__ . "/custom_config.js");
```

That would be  in my opinion the easiest and fastest solution. Custom_config.js are simple and quick to configure, etc...

From a quick question, how you have solved. Listen with delight! Thank you in advance!

**Comment by spekary** [comment]
I just added a configuration option with example. Try that.

**Comment by vaibhav-kaushal** [comment]
@kukrik It was #10 .

**Comment by vaibhav-kaushal** [comment]
I am able to do this on my end. Closing the issue.
